= Power and Network Ethernet Interface

[IMPORTANT]
====
In addition to this guide, obey all instructions given in the user manual that was shipped with the unit.
====

== Requirements

* For operating the Qb device, Power over Ethernet (PoE) must be available. The corresponding networking equipment must support Type 1 powered devices (IEEE 802.3at).
* Use only power supplying equipment that complies with the relevant national regulations and standards for electrical safety.
* Custom electrical installations or permanent installations inside of buildings must be carried out by qualified electricians.
* Use a shielded Ethernet cable that is IEEE 802.3at-compliant and has a rating of at least Cat. 5e with a suitable M12 connector on the sensor side. Obey the minimum bending radius specified by the manufacturer.
* When bundling cables, obey the applicable regulations and technical guidelines regarding the number of bundled cables and required wire cross-sections.

[TIP]
====
Find more details regarding the Ethernet connector and PoE in the xref:connection.adoc[Ethernet interface description]. +
Blickfeld offers pre-assembled cables with the Qb-specific connector. Contact sales@blickfeld.com for further information.
====

== How to connect

* Remove the protective cap from the Ethernet port. Connect the Qb device to a Power-over-Ethernet power-supplying equipment using a cable with a matching connector. Observe the correct connector orientation and hand-tighten only.
* Optionally, when using the WiFi feature: Remove the protective cap from the antenna port. Attach the antenna and hand-tighten it only.
* When bundling cables, obey the applicable regulations and technical guidelines regarding the number of bundled cables and required wire cross-sections.
* Keep protective caps attached to unused equipment ports.
* Use appropriate PoE surge protection in outdoor installations.

Once power is supplied to the sensor, it will automatically start into an idle state in which the web interface is available but laser scanning has not yet startet. Scanning starts automatically once a point cloud is requested from the sensor or the web viewer is opened.

[NOTE]
After switching on the power to the Qb device, it can take up to 120 seconds until the Qb device is ready for use.


.Wiring diagram for a simple indoor installation.
image::Qb2_Wiring_diagram.svg[width=640]

. Host computer
. Qb device
. PoE injector
. PoE network switch

== Outdoor installation

When the sensor is installed outdoors some additional aspects should be considered in order to protect the sensor and connected equipment from environmental influences.

=== Cabling best practices

Cable drip loop::
While the Qb device has a certified ingress protection rating of IP67, long-term exposure to moisture should be avoided as much as possible in order to prolong product life span. In particular, it is recommended to mount and connect the sensor in a way that allows it to dry-off quickly.
A cable drip loop helps in protecting the electrical connector from prolonged exposure to moisture. An example is shown in the image below. The basic idea is to have the cable make a turn in a location below the sensor installation height. In this way any water drops forming on the cable drip down at the turning point instead of wetting the electrical connector.

.Basic concept of a drip loop.
image::Qb2_drip_loop.svg[width=320]

Cable length::
The PoE standard supports cable lenths of up to 100 meters. Consider using fiber-optical communication for long distances instead. If only perception data and no live point cloud data is needed, the sensor's WiFi feature might also be an option.

=== Surge protection

When mounted outdoors, and in particular when placed on elevated structures such as lighting poles, surges due to lightning strike present a hazard to electrical equipment that is connected to the sensor. In order to protect building installations, it is recommended to use appropriate surge protection devices (SPDs) close to the Qb device as well as close to the building to which the sensor is connected.

.Surge protection in outdoor installations.
image::Qb2_surge_protection.svg[width=400]

. Qb device mounted to pole
. Outdoor surge protection devices (SPDs)
. PoE Gigabit power supplying equipment
. To network building installation
