= Service: States

NOTE: This API is officially released and maintained.

An RPC service to request a stream of states messages. If a pipeline is 
already running, it will be used to stream the data. If no pipeline is 
running, it will be started first and then the stream will start. NOTE: in 
this second case, the pipeline will also be automatically stopped once 
there are no more clients requesting any stream type from the module.

.Available methods
|===
| Method | Request | Response

| *xref:#Stream[]* | xref:#_google_protobuf_Empty[google.protobuf.Empty]| xref:blickfeld/percept_processing/services/states.adoc#_blickfeld_percept_processing_services_StatesStreamResponse[StatesStreamResponse]Stream 
|===
[#Stream]
== Stream

A method to get a stream of states messages from the pipeline

[#_blickfeld_percept_processing_services_StatesStreamResponse]
=== Response Stream

A response for getting a stream of states messages from the running 
pipeline

.Available fields in blickfeld.percept_processing.services.StatesStreamResponse
|===
| Field | Type | Default | Unit

.2+| *states* | xref:blickfeld/percept_processing/data/states.adoc#_blickfeld_percept_processing_data_States[data.States] | - | - 
3+| The current states with the information detected in the scene.

|===

