[#_blickfeld_diagnostics_data_Log]
= Log

This message aggregates the data structures related to the log service.

[#_blickfeld_diagnostics_data_Log_Entry]
== Entry

The log entry contains the message and metadata of a log.

.Available fields in blickfeld.diagnostics.data.Log.Entry
|===
| Field | Type | Default | Unit

.2+| *boot_uuid* | string| - | - 
3+| UUID of the boot during which the log was written.

.2+| *cursor* | xref:blickfeld/diagnostics/data/log.adoc#_blickfeld_diagnostics_data_Log_Entry_Cursor[Cursor] | - | - 
3+| Cursor used to index log entries and to navigate through the logs.

.2+| *timestamp* | uint64| - | ns 
3+| The wallclock time at the point in time the entry was received by the journal, in nanoseconds since the epoch UTC.

.2+| *module* | xref:blickfeld/diagnostics/config/log.adoc#_blickfeld_diagnostics_config_Log_Filter_SoftwareModule[config.Log.Filter.SoftwareModule] | - | - 
3+| The module which has written the log.

.2+| *level* | xref:blickfeld/diagnostics/data/log.adoc#_blickfeld_diagnostics_data_Log_Entry_Level[Level] | - | - 
3+| The log level of the log.

.2+| *message* | string| - | - 
3+| The message which has been logged.

|===

[#_blickfeld_diagnostics_data_Log_Entry_Cursor]
=== Cursor

The cursor uniquely identifies a log entry in the logs.

.Available fields in blickfeld.diagnostics.data.Log.Entry.Cursor
|===
| Field | Type | Default | Unit

.2+| *sequence_number_id* | string| - | - 
3+| The sequence number ID is used to reference a set of log entries generated by the same systemd-journald instance.

.2+| *sequence_number* | uint64| - | - 
3+| The sequence number is assigned to a log entry by the systemd-journald instance when they are written to disk. 
Every instance numbers their entries sequentially, starting from 1 for the first entry written after subsystem 
initialization.

|===

[#_blickfeld_diagnostics_data_Log_Entry_Level]
=== Level

The log level represents the priority of the log.

.Available values for blickfeld.diagnostics.data.Log.Entry.Level enum
[cols='25h,5,~']
|===
| Name | Value | Description

| LEVEL_UNSPECIFIED ^| 0 | No level is set
| LEVEL_ERROR ^| 1 | An error condition was detected 
 
Includes the systemd levels: EMERGENCY, ALERT, CRITICAL, ERROR
| LEVEL_WARNING ^| 2 | The message indicates that an error will occur if no action is taken 
 
Includes the systemd levels: NOTICE, WARNING
| LEVEL_INFO ^| 3 | Normal operational messages that require no action 
 
Includes the systemd levels: INFORMATIONAL
|===

