antora:
  extensions:
  # Enable search field
  - require: '@antora/lunr-extension'
    index_latest_only: true
content:
  edit_url: ~
  sources:
  - start_path: doc
    url: .
    # We only show major.minor version, no patch releases
    tags: ['v*', '!v*.*.*']
output:
  clean: false
  dir: ./public
site:
  url: https://docs.blickfeld.com/qb2
  start_page: Qb2::index.adoc
  title: Qb2 Documentation
  robots: allow
ui:
  bundle:
    snapshot: true
    url: /ci-helper/ui-bundle.zip
  supplemental_files: /ci-helper/opt/antora/.nvm/default/lib/node_modules/@antora/lunr-extension/data