[#_blickfeld_beam_deflection_control_data_Health]
= Health

Health message containing information about operation, status and error of a beam deflection controller.

.Available fields in blickfeld.beam_deflection_control.data.Health
|===
| Field | Type | Default | Unit

.2+| *state* | xref:blickfeld/base/data/health.adoc#_blickfeld_base_data_Health_State[base.data.Health.State] | - | - 
3+| High-level state of module

.2+| *state_reason* | string| - | - 
3+| Reason for given state. Is not set if state is OK.

.2+| *stats* | xref:blickfeld/beam_deflection_control/data/health.adoc#_blickfeld_beam_deflection_control_data_Health_Stats[Stats] | - | - 
3+| Stats giving basic information about the mirror operation

|===

[#_blickfeld_beam_deflection_control_data_Health_Stats]
== Stats

This message defines the stats that can be retrieved from a beam deflection controller.

.Available fields in blickfeld.beam_deflection_control.data.Health.Stats
|===
| Field | Type | Default | Unit

.2+| *time* | float| - | s 
3+| Time in seconds since last operation start.

.2+| *control_effort* | float| - | - 
3+| Control effort usage. Relative value indicating how much of the maximum available effort is currently used 
to control the deflection mirror.

|===

