[#_blickfeld_base_data_Health]
= Health

The Health message and corresponding services are used to indicate their health & status. 
 
They are available on different layers. 
Upstream / higher layers usually aggregate the Health of their child modules. 
In the end, the goal is, to get an aggregated product Health which reliably indicates if everything is functional.

[#_blickfeld_base_data_Health_State]
== State

High-level state which indicates the current health state of the module. 
If the State is not OK, please refer to the details fields in the Health message to trace the root cause.

.Available values for blickfeld.base.data.Health.State enum
[cols='25h,5,~']
|===
| Name | Value | Description

| STATE_UNSPECIFIED ^| 0 | The current state is unknown.
| STATE_OK ^| 1 | Everything is perfect.
| STATE_WARNING ^| 2 | There are non-critical errors. 
This might result in unexpected error and should be investigated for production set-ups.
| STATE_FAILED ^| 3 | The module is in a failed state and can no longer operate.
| STATE_BUSY ^| 4 | The module is currently busy. 
Requests might get aborted or delayed.
|===

