= Events

In addition to the video stream of the security scene, https://www.blickfeld.com/lidar-sensor-products/qbprotect/[QbProtect] also utilizes ONVIF events which can be used by various applications to fulfill a desired action. The list of supported ONVIF event mechanisms is summarized in the <<events-table,Table {counter:table}>> below.

[[events-table]]
.ONVIF event mechanisms supported by QbProtect
[cols="1,1,1,3",options="header"]
|===
| Mechanism | Supported | Protocol | Direction

| Pull-Point
| ✅
| SOAP / HTTP
| VMS -> QbProtect (polling)

| Base Notification
| ✅
| SOAP / HTTP
| QbProtect -> VMS (pushing)

| Replay
| ❌
| SOAP / HTTP
| Both

| RTSP Metadata
| ❌
| RTSP/RTP
| 

|===

The list of supported events, their description and type are shown in the <<events-list,Table {counter:table}>> below.

[NOTE]
====
Events origininating from dynamic event sources (e.g. intrusion event from a particular security zone) are called `Dynamic`. Other events are called `Static`. The https://www.blickfeld.com/lidar-sensor-products/qbprotect/[QbProtect] has to be re-added into VMS in oder to expose events from dynamic sources newly configured via QbProtect xref:introduction:webgui_tutorial.adoc[WebGUI].
====


[[events-list]]
.QbProtect ONVIF events
[%header,cols="1,4,1"]
|===
|Name | Description| Availability

a|[,console]
----
tns1:VideoSource/MotionAlarm
----
| Motion event in the observed security scene | Static


a|[,console]
----
tns1:Blickfeld/Intrusion
----
| Aggregated intrusion event in pre-configured security zones. Security zones that are configured in QbProtect WebGUI but are not used as ONVIF event sources are also considered as sources for this event. | Static

a|[,console]
----
tns1:Blickfeld/IntrusionZone{Name}
----
| Intrusion event in the pre-configured intrusion zone, where {Name} is replaced by the name of the configured zone (e.g., if the zone is called "Gate One", then the corresponding event will be called `IntrusionZoneGateOne` ) | Dynamic

a|[,console]
----
tns1:Blickfeld/HealthFailure
----
| QbProtect is in the failed state (one or more failures). The actual root cause can be found at QbProtect diagnostics page | Static

a|[,console]
----
tns1:Blickfeld/HealthWarning
----
| QbProtect is in the warning state (one or more warnings). The actual root cause can be found at QbProtect diagnostics page | Static

a|[,console]
----
tns1:Blickfeld/TamperingCovered
----
| The window of QbProtect has been covered | Static

a|[,console]
----
tns1:Blickfeld/TamperingMoved
----
| QbProtect has been moved or rotated | Static


a|[,console]
----
tns1:Blickfeld/Tampering
----

| QbProtect has been either moved or covered | Static
|===


.Only for existing ONVIF setups with version JACK v2.9 and below
[IMPORTANT]
====
ONVIF events delivered with firmware version https://github.com/Blickfeld/blickfeld-qb2/releases/tag/v2.9[JACK v2.9] and below are considered to be legacy. They remain functional in the existing QbProtect setups after firmware upgrades; however, they will not be further expanded. To obtain the most recent list of supported events after the installation of a newer firmware release, please follow the procedure below:

1. Remove all existing ONVIF HTTP xref:working_principles:authentication.adoc#_application_key[application keys] from all configured user accounts
2. Reboot QbProtect

Once fulfilled, the new event list is persistently exposed for the configuration in your VMS system.
====