= Application Programming Interface (API)

Qb2 utilizes a TLS-secured https://grpc.io/[gRPC] network protocol.
The modern framework provides client libraries for various languages and platforms and therefore allows a simple and efficient integration in customer applications.

gRPC implements a remote procedure call (RPC) pattern grouping RPC calls into so-called services.
RPC calls (= methods) usually have one request and one response.
Additionally, streams are supported for continuous data transport effectively emitting multiple requests and responses.
On top of this, the Blickfeld API groups the methods by module namespaces to give them a context and allow
the reutilization of service names with similar behaviors in multiple modules.

The corresponding `.proto` files are publicly available on https://github.com/Blickfeld/blickfeld-qb2[Github].
A rendered version of the protocol files can be found in the sub-navigation tree of this section.
The documentation provides a complete overview of all available methods, data structures, and fields.
Note that fields might have a varying format on different platforms e.g. Python uses snake_case and Typescript uses CamelCase.
