= Electrical Installation

[IMPORTANT]
====
In addition to this guide, obey all instructions given in the user manual that was shipped with the unit. 
====

== Requirements

* For operating the Qb2, Power over Ethernet (PoE) must be available. The corresponding networking equipment must support Type 1 powered devices (IEEE 802.3at).
* Use only power supplying equipment that complies with the relevant national regulations and standards for electrical safety.
* Custom electrical installations or permanent installations inside of buildings must be carried out by qualified electricians.
* Use a shielded Ethernet cable that is IEEE 802.3at-compliant and has a rating of at least Cat. 5e with a suitable M12 connector on the sensor side. Obey the minimum bending radius specified by the manufacturer.
* When bundling cables, obey the applicable regulations and technical guidelines regarding the number of bundled cables and required wire cross-sections. 

[TIP]
====
Find more details regarding the Ethernet connector and PoE in the xref:foundations:ethernet_interface.adoc[Ethernet interface description]. +
Blickfeld offers pre-assembled cables with the Qb2-specific connector. Contact sales@blickfeld.com for further information.
====

== How to connect

. Unscrew the protective cap from the Ethernet connector of the Qb2.
. Connect the Ethernet cable to the Qb2 by screwing on the M12 connector and *hand-tighten*. The cable connector fits in only one orientation given by the alignment key in the center.
. (Optional: Attached the supplied WiFi antenna and *hand-tighten*.)
. Connect the Ethernet cable to the network installation or switch on Power over Ethernet.

Once power is supplied to the sensor, it will automatically start into an idle state in which the web interface is available but laser scanning has not yet startet. Scanning starts automatically once a point cloud is requested from the sensor or the web viewer is opened.

.Wiring diagram for a simple indoor installation.
image::Qb2_Wiring_diagram.svg[width=640, xref=qb2-wiring]

. Host computer
. Qb2
. PoE injector
. PoE network switch

== Outdoor installation

When the sensor is installed outdoors some additional aspects should be considered in order to protect the sensor and connected equipment from environmental influences.

=== Cabling best practices

Cable drip loop::
While the Qb2 has a certified ingress protection rating of IP67, long-term exposure to moisture should be avoided as much as possible in order to prolong product life span. In particular, it is recommended to mount and connect the sensor in a way that allows it to dry-off quickly. 
A cable drip loop helps in protecting the electrical connector from prolonged exposure to moisture. An example is shown in the image below. The basic idea is to have the cable make a turn in a location below the sensor installation height. In this way any water drops forming on the cable drip down at the turning point instead of wetting the electrical connector.

.Basic concept of a drip loop.
image::Qb2_drip_loop.svg[width=320, xref=drip-loop]

Cable length::
The PoE standard supports cable lenths of up to 100 meters. Consider using fiber-optical communication for long distances instead. If only perception data and no live point cloud data is needed, the sensor's WiFi feature might also be an option.

=== Surge protection

When mounted outdoors, and in particular when placed on elevated structures such as lighting poles, surges due to lightning strike present a hazard to electrical equipment that is connected to the sensor. In order to protect building installations, it is recommended to use appropriate surge protection devices (SPDs) close to the Qb2 as well as close to the building to which the sensor is connected. 

.Surge protection in outdoor installations.
image::Qb2_surge_protection.svg[width=400, xref=surge-protection]

. Qb2 mounted to pole
. Outdoor surge protection devices (SPDs)
. PoE Gigabit power supplying equipment
. To network building installation