[#_blickfeld_percept_pipeline_config_DataSource]
= Data Source

The configuration storing the sources to retrieve the point cloud data for further processing.

.Available fields in blickfeld.percept_pipeline.config.DataSource
|===
| Field | Type | Default | Unit

.2+| *qb2_setup* | xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Qb2Setup[Qb2Setup] | - | - 
3+| Use Qb2 lidars to retrieve point clouds

.2+| *geolocation_of_map* | optional xref:blickfeld/base/config/geolocation.adoc[base.config.Geolocation] | - | - 
3+| Geolocation of data source. 
This references the map coordinate system of this data source to the world. 
Individual lidars are referenced to the map coordinate system via their `map_from_lidar` transform. 
 
[NOTE] 
If the map_from_lidar transform is not an identity transformation, this is not the geolocation of an individual sensor.

.2+| *swarm* | xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Swarm[Swarm] | - | - 
3+| Mode which enables configuration synchronization and distributed processing. 
 
Processing and synchronization is managed by a dedicated leader sensor. 
All processing-related configuration, e.g. scan pattern and perception parameters are 
synchronized from the leader sensor onto every follower sensor in the sensor setup. 
 
The object lists and foreground point clouds of all sensors are fused and processed on the 
leader sensor of the swarm. This will allow processing of object-based security zones 
and point-based security zones across the combined field of view.

.2+| *allow_unavailable_lidars* | bool| - | - 
3+| Allow that devices in the setup are temporarily not available or failed. 
 
Re-connection attempts are performed continuously. 
A warning with the list of unavailable sensors is raised. 
If all sensors are unavailable, the pipeline will fail.

|===

[#_blickfeld_percept_pipeline_config_DataSource_Qb2]
== Qb2

Configuration for retrieving point clouds from a Qb2

.Available fields in blickfeld.percept_pipeline.config.DataSource.Qb2
|===
| Field | Type | Default | Unit

.2+| *fqdn* | optional string| - | - 
3+| The fully qualified domain name of the Qb2 device. For on-device processing/configuration, 'fqdn' can be set 
to an empty string to request the data of the current device.

.2+| *port* | optional uint32| - | - 
3+| The gRPC port of the Qb2 device. If unset the default gRPC ports 50051 (unencrypted) or 55551 (TLS) will be used.

.2+| *map_from_lidar* | optional xref:blickfeld/base/geometry/transform.adoc[base.geometry.Transform] | - | - 
3+| Transformation from the lidar frame to the map frame. If this transform is not set, this will be interpreted as identify 
transformation. Transforming all point cloud topics into the map frame results in a globally consistent combined point cloud in 
map frame.

.2+| *application_key* | optional string| - | - 
3+| Application key with authorized access level. If set, the field serial_number has to be set as well. 
This field is required if user-management is enabled on externally connected devices.

.2+| *serial_number* | optional string| - | - 
3+| Serial number. If set, the connection will be secured with TLS. This field is required if user-management 
is enabled on externally connected devices.

.2+| *disabled* | bool| - | - 
3+| Disable fetching data from this sensor, setting this flag to `true` disables the evaluation of the entire sensor point cloud

.2+| *metadata* | optional https://protobuf.dev/reference/protobuf/google.protobuf/#struct[google.protobuf.Struct] | - | - 
3+| Arbitrary metadata storage for client applications

|===

[#_blickfeld_percept_pipeline_config_DataSource_Trigger]
== Trigger

Configuration of Trigger Mode. In trigger mode the processing pipeline will reduce the frequency at which 
point clouds and state lists are getting computed to reduce the amount of data transmitted between the processing 
device and configured 'lidars'.

.Available fields in blickfeld.percept_pipeline.config.DataSource.Trigger
|===
| Field | Type | Default | Unit

.2+| *frequency* | float| - | Hz 
3+| The frequency at which data is getting requested from the lidars and outputs are generated.

|===

[#_blickfeld_percept_pipeline_config_DataSource_Qb2Setup]
== Qb2 Setup

The configuration of a Qb2 setup of the LiDAR devices

.Available fields in blickfeld.percept_pipeline.config.DataSource.Qb2Setup
|===
| Field | Type | Default | Unit

.2+| *lidars* | repeated xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Qb2[Qb2] | - | - 
3+| the qb2 lidars to get the point clouds from

.2+| *trigger* | optional xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Trigger[Trigger] | - | - 
3+| If the field is set trigger mode is enabled. If the field is not set, the pipeline outputs are computed 
with the frequency of configured lidars, i.e. the scan pattern configured on those.

|===

[#_blickfeld_percept_pipeline_config_DataSource_Swarm]
== Swarm

Configuration options for Swarm mode

.Available fields in blickfeld.percept_pipeline.config.DataSource.Swarm
|===
| Field | Type | Default | Unit

.2+| *leader* | bool| - | - 
3+| This device is the swarm leader.

.2+| *follower* | xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Qb2[Qb2] | - | - 
3+| This device is managed by another device.

.2+| *synchronization_delay* | float| - | s 
3+| Maximum latency of the data fusion in swarm mode: 
after the leader's own frame is ready for fusion, the leader waits at most this long for the 
matching data of all remote devices. Fusion is triggered immediately once all expected remote 
data has been received. (default: 1 second)

.2+| *metadata* | optional https://protobuf.dev/reference/protobuf/google.protobuf/#struct[google.protobuf.Struct] | - | - 
3+| Arbitrary metadata storage for client applications

|===

