[#_blickfeld_percept_pipeline_config_DataSource]
= Data Source

The configuration storing the sources to retrieve the point cloud data for further processing.

.Available fields in blickfeld.percept_pipeline.config.DataSource
|===
| Field | Type | Default | Unit

.2+| *qb2_setup* | xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Qb2Setup[Qb2Setup] | - | - 
3+| Use Qb2 lidars to retrieve point clouds

.2+| *geolocation_of_map* | optional xref:blickfeld/base/config/geolocation.adoc[base.config.Geolocation] | - | - 
3+| Geolocation of data source. 
This references the map coordinate system of this data source to the world. 
Individual lidars are referenced to the map coordinate system via their `map_from_lidar` transform. 
 
[NOTE] 
If the map_from_lidar transform is not an identity transformation, this is not the geolocation of an individual sensor.

.2+| *swarm* | bool| - | - 
3+| Experimental mode which enables configuration synchronization and distributed processing. 
 
All processing-related configuration, e.g. scan pattern and zones, are automatically 
synchronized between all members in the sensor setup. 
Also the sensor setup itself is replicated on all sensors. 
 
The object lists of all sensors are fused and tracked on every member in the swarm. 
Thus, also all object-based security zones are evaluated on every sensor. 
This leads to a high availablity and redundancy without requiring a master processing 
unit would be a single point of failure.

|===

[#_blickfeld_percept_pipeline_config_DataSource_Qb2]
== Qb2

Configuration for retrieving point clouds from a Qb2

.Available fields in blickfeld.percept_pipeline.config.DataSource.Qb2
|===
| Field | Type | Default | Unit

.2+| *fqdn* | string| - | - 
3+| The fully qualified domain name of the Qb2 device. For on-device processing/configuration, 'fqdn' can be set 
to an empty string to request the data of the current device.

.2+| *map_from_lidar* | xref:blickfeld/base/geometry/transform.adoc[base.geometry.Transform] | - | - 
3+| Transformation from the lidar frame to the map frame. If this transform is not set, this will be interpreted as identify 
transformation. Transforming all point cloud topics into the map frame results in a globally consistent combined point cloud in 
map frame.

.2+| *application_key* | optional string| - | - 
3+| Application key with authorized access level. Required if user-management is enabled on externally connected devices.

.2+| *serial_number* | optional string| - | - 
3+| Serial number. Required if user-management is enabled on externally connected devices.

.2+| *metadata* | optional https://protobuf.dev/reference/protobuf/google.protobuf/#struct[google.protobuf.Struct] | - | - 
3+| Arbitrary metadata storage for client applications

|===

[#_blickfeld_percept_pipeline_config_DataSource_Trigger]
== Trigger

Configuration of Trigger Mode. In trigger mode the processing pipeline will reduce the frequency at which 
point clouds and state lists are getting computed to reduce the amount of data transmitted between the processing 
device and configured 'lidars'.

.Available fields in blickfeld.percept_pipeline.config.DataSource.Trigger
|===
| Field | Type | Default | Unit

.2+| *frequency* | float| - | Hz 
3+| The frequency at which data is getting requested from the lidars and outputs are generated.

|===

[#_blickfeld_percept_pipeline_config_DataSource_Qb2Setup]
== Qb2 Setup

The configuration of a Qb2 setup of the LiDAR devices

.Available fields in blickfeld.percept_pipeline.config.DataSource.Qb2Setup
|===
| Field | Type | Default | Unit

.2+| *lidars* | repeated xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Qb2[Qb2] | - | - 
3+| the qb2 lidars to get the point clouds from

.2+| *trigger* | optional xref:blickfeld/percept_pipeline/config/data_source.adoc#_blickfeld_percept_pipeline_config_DataSource_Trigger[Trigger] | - | - 
3+| If the field is set trigger mode is enabled. If the field is not set, the pipeline outputs are computed 
with the frequency of configured lidars, i.e. the scan pattern configured on those.

|===

