[#_blickfeld_percept_pipeline_config_ZoneAlgorithm]
= Zone Algorithm

An algorithm that monitors the area within and around a zone.

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm
|===
| Field | Type | Default | Unit

.2+| *name* | string| - | - 
3+| The user readable zone algorithm name

.2+| *uuid* | string| - | - 
3+| The uuid of the zone algorithm (uuid4)

.2+| *shape* | xref:blickfeld/base/geometry/shape.adoc[base.geometry.Shape] | - | - 
3+| Geometric shape (usually a Box) in which the algorithm detects certain behaviors/scenarios

.2+| *disabled* | bool| - | - 
3+| Disable this zone, setting this flag to `true` disables the evaluation of the zone

.2+| *geolocation* | optional xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Geolocation[Geolocation] | - | - 
3+| Geolocation of the zone. 
 
This field is read only and only set when the geolocation is configured in the data source.

.2+| *metadata* | optional https://protobuf.dev/reference/protobuf/google.protobuf/#struct[google.protobuf.Struct] | - | - 
3+| Arbitrary metadata storage for client applications

.2+| *volume* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Volume[Volume] | - | - 
3+| Run volume monitoring within the zone

.2+| *security* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Security[Security] | - | - 
3+| Run alarm detection within the zone

.2+| *exclusion* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Exclusion[Exclusion] | - | - 
3+| Run exclusion zone

.2+| *object_based_security* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_ObjectBasedSecurity[ObjectBasedSecurity] | - | - 
3+| Run object-based alarm detection within the zone

.2+| *occupancy* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Occupancy[Occupancy] | - | - 
3+| Run occupancy zone

.2+| *traversal_security* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_TraversalSecurity[TraversalSecurity] | - | - 
3+| Run traversal zone

.2+| *traffic_lane* | xref:blickfeld/percept_pipeline/config/zone_algorithm.adoc#_blickfeld_percept_pipeline_config_ZoneAlgorithm_TrafficLane[TrafficLane] | - | - 
3+| Run traffic monitoring within the zone

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Geolocation]
== Geolocation

The geolocation of the zone based on the map and the zone position.

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.Geolocation
|===
| Field | Type | Default | Unit

.2+| *center* | xref:blickfeld/base/config/geolocation.adoc[base.config.Geolocation] | - | - 
3+| The geolocation of the center of the zone.

.2+| *corners* | repeated xref:blickfeld/base/config/geolocation.adoc[base.config.Geolocation] | - | - 
3+| The geolocation of the corners of the zone.

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Volume]
== Volume

Algorithm that measure the volume of a zone 
 
The volume of a zone is approximated by computing a 'volume map' from the input point clouds. The volume map discretizes the zone 
into 'tiles' in the xy-plane with a side-length of 'resolution'. Each tile contains the height information about the points that 
fall into this tile. The volume of the volume map can be calculated by adding up the volumes of the tiles in the volume map.

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.Volume
|===
| Field | Type | Default | Unit

.2+| *resolution* | float| - | m 
3+| Grid resolution per tile used to measure the volume. 
 
Reasonable default: 0.1

.2+| *empty_volume* | float| - | m^3 
3+| The measured volume while area covered by the zone is considered 'empty'. The value can be set using 
TareVolume method while the area of the zone is empty. 
 
Reasonable default: 0

.2+| *disable_when_occupied_zone_uuids* | repeated string| - | - 
3+| Link volume zone to occupancy zones (by uuid). 
 
Disables the volume zone state when one of the occupancy zones is occupied.

.2+| *angle_of_repose* | optional float| - | rad 
3+| Angle of repose. 
 
Steepest angle of descent when the measured material is piled. 
See https://en.wikipedia.org/wiki/Angle_of_repose.

.2+| *minimum_coverage* | optional float| - | - 
3+| Minimum coverage value for zone. 
 
When the estimated coverage is below the configured threshold, 
the state output will be disabled. 
 
This can be used to automatically disable zones when the viewport to the 
zone area is blocked or the sensor is temporarily failed. 
 
Default: 0

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Security]
== Security

Algorithm that triggers an alarm if movement was detected in the zone

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.Security
|===
| Field | Type | Default | Unit

.2+| *min_points* | uint32| - | - 
3+| Minimum number of (foreground) points in the security zone to trigger the alarm. 
Reasonable default: 10

.2+| *max_points* | uint32| - | - 
3+| Maximum number of (foreground) points in the security zone that still triggers an alarm. 
More points will disable the alarm. This logic can be disabled by setting max_points to '0'. 
Default: 0

.2+| *minimum_intruding_duration* | float| - | s 
3+| Minimum active intrusion duration before alarm is triggered. 
 
Default: 0

.2+| *minimum_intrusion_confidence* | float| - | - 
3+| Minimum intrusion confidence before alarm is triggered. 
 
Only applicable when the minimum intruding duration is configured. 
 
Default: 1

.2+| *hold_duration* | float| - | s 
3+| Alarm is kept active for the given duration to reduce jitter. 
 
Default: 0

.2+| *disable_when_occupied_zone_uuids* | repeated string| - | - 
3+| Link security zone to occupancy zones (by uuid). 
 
Disables the security zone state and alarms when one of the occupancy zones is occupied.

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_ObjectBasedSecurity]
== Object Based Security

Algorithm that triggers an alarm when an object of one of the selected sizes is in the zone

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.ObjectBasedSecurity
|===
| Field | Type | Default | Unit

.2+| *alarm_sizes* | repeated xref:blickfeld/percept_pipeline/config/object_size.adoc[ObjectSize] | - | - 
3+| Selection of sizes which trigger an alarm. Each size in the array will only 
trigger an alarm for the interval of that size.

.2+| *minimum_intruder_lifetime* | float| - | s 
3+| Minimum lifetime of object before alarm is triggered. 
 
Default: 0

.2+| *minimum_intruder_track_length* | float| - | m 
3+| Minimum track length of object before alarm is triggered. 
 
Default: 0

.2+| *minimum_intruding_duration* | float| - | s 
3+| Minimum active intrusion duration before alarm is triggered. 
 
Default: 0

.2+| *objects_in_background* | bool| - | - 
3+| Trigger alarm for objects with the "in_background" property. 
 
Enabling this might increase the false alarm rate.

.2+| *minimum_intrusion_confidence* | float| - | - 
3+| Minimum intrusion confidence before alarm is triggered. 
 
Only applicable when the minimum intruding duration is configured. 
 
Default: 1

.2+| *hold_duration* | float| - | s 
3+| Alarm is kept active for the given duration to reduce jitter. 
 
Default: 0

.2+| *intrusion_on_partial_entry* | bool| - | - 
3+| Detect an object as intruder if any part of it enters the zone. 
Only the center point of the object is considered when disabled. 
 
Enabling this might increase the false alarm rate.

.2+| *disable_when_occupied_zone_uuids* | repeated string| - | - 
3+| Link security zone to occupancy zones (by uuid). 
 
Disables the security zone state and alarms when one of the occupancy zones is occupied.

.2+| *intrusion_on_wrong_direction* | bool| - | - 
3+| Detect an object as intruder if it is moving in the wrong direction, similar to the directional zone, 
but covering an area.

.2+| *minimum_intruder_velocity* | float| - | m/s 
3+| Minimum velocity an intruder has to have to trigger an intrusion on wrong direction. Prevents standing objects or persons from 
triggering a false alarm. 
 
Only applicable if intrusion on wrong direction is enabled. 
 
Default: 0.028 (equals 0.1 km/h)

.2+| *minimum_average_intruder_intensity* | optional float| - | - 
3+| Minimum average intensity an intruder has to have to trigger an intrusion. 
 
This allows filtering false alarms when they have a significantly different intensity level than real objects. 
 
Default: 0 (all average intensity values are considered)

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Exclusion]
== Exclusion

Algorithm that excludes points from the input point cloud

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_Occupancy]
== Occupancy

Algorithm that detects if a zone is occupied

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.Occupancy
|===
| Field | Type | Default | Unit

.2+| *min_points* | uint32| - | - 
3+| Minimum number of points to mark the zone as occupied. 
 
Reasonable default: 10

.2+| *adaptive_baseline_time_constant* | optional float| - | s 
3+| If set, the min_points is not compared against zero but against an 
adaptive baseline. The baseline is calculated with an exponential 
filter with the zone point count as input. 
 
The given time constant is used to calculate the alpha for the exponential 
filter. After a restart, the baseline is initialized with the current zone 
point count. 
 
Reasonable default: 3600s (1 hour)

.2+| *voxel_size* | optional float| - | m 
3+| The point cloud inside the zone is down sampled with a voxel grid. 
This is done to achieve a distance-independent parametrization. 
The size of a voxel cell can be configured with this parameter. 
 
Default: 0.05m

.2+| *invert* | bool| - | - 
3+| Invert the state of the zone 
 
This might be useful in situations where e.g. a static crane should be detected in its home position.

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_TraversalSecurity]
== Traversal Security

Algorithm that detects if objects are traversing through the zone.

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.TraversalSecurity
|===
| Field | Type | Default | Unit

.2+| *alarm_sizes* | repeated xref:blickfeld/percept_pipeline/config/object_size.adoc[ObjectSize] | - | - 
3+| Selection of sizes which trigger an alarm.  An alarm will only be triggered by objects of sizes 
specified in the array.

.2+| *hold_duration* | float| - | s 
3+| Alarm is kept active for the given duration to reduce jitter. 
 
Default: 0

.2+| *disable_when_occupied_zone_uuids* | repeated string| - | - 
3+| Link security zone to occupancy zones (by uuid). 
 
Disables the security zone state and alarms when one of the occupancy zones is occupied.

|===

[#_blickfeld_percept_pipeline_config_ZoneAlgorithm_TrafficLane]
== Traffic Lane

Algorithm that monitors traffic moving through the zone.

.Available fields in blickfeld.percept_pipeline.config.ZoneAlgorithm.TrafficLane
|===
| Field | Type | Default | Unit

.2+| *expected_velocity* | float| - | m/s 
3+| Expected velocity of the objects inside the traffic zone.

|===

