= Service: Device Operation

NOTE: This API is officially released and maintained.

This service is used for starting and stopping the device operation. 
Normally, the device is started and stopped based on the client connections. If there is a client using the Qb2, the 
device will start and stay in operation until all clients disconnected. The start function of this service overrides 
this behaviour, i.e. when started using the start function the device will stay operational even though no clients 
are connected. This allows a faster retrieval of frames once a client connects as the startup phase is skipped.

.Available methods
|===
| Method | Request | Response

| *xref:#Start[]* | https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]| https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]
| *xref:#Stop[]* | https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]| https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]
| *xref:#Get[]* | https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]| xref:blickfeld/hardware/services/device_operation.adoc#_blickfeld_hardware_services_DeviceOperationGetResponse[DeviceOperationGetResponse]
| *xref:#Watch[]* | https://protobuf.dev/reference/protobuf/google.protobuf/#empty[google.protobuf.Empty]| xref:blickfeld/hardware/services/device_operation.adoc#_blickfeld_hardware_services_DeviceOperationWatchResponse[DeviceOperationWatchResponse]Stream 
|===
[#Start]
== Start

Method to start the device operation. 
This starts the operation ot the deflection mirrors and the laser triggering. 
When this call is used, the device will stay in operation until stop is called 
(independent of clients being connected or not).

[#Stop]
== Stop

Method to stop the device operation. 
This stops the triggering the laser and the movement of the deflection mirrors.

[#Get]
== Get

Get the current status of the device operation

[#_blickfeld_hardware_services_DeviceOperationGetResponse]
=== Response

Response containing the current device operation state

.Available fields in blickfeld.hardware.services.DeviceOperationGetResponse
|===
| Field | Type | Default | Unit

.2+| *device_operation* | xref:blickfeld/hardware/data/device_operation.adoc[data.DeviceOperation] | - | - 
3+| device operation state

|===

[#Watch]
== Watch

Subscribe to status updates of the device operation

[#_blickfeld_hardware_services_DeviceOperationWatchResponse]
=== Response Stream

Response containing the current device operation state

.Available fields in blickfeld.hardware.services.DeviceOperationWatchResponse
|===
| Field | Type | Default | Unit

.2+| *device_operation* | xref:blickfeld/hardware/data/device_operation.adoc[data.DeviceOperation] | - | - 
3+| device operation state

|===

