= Video Management Systems (VMS)

Due to the interoperability of the ONVIF protocol, https://www.blickfeld.com/lidar-sensor-products/qbprotect/[QbProtect] is not restricted to a particular VMS manufacturer and may work with any VMS supporting ONVIF;  however, it is actively tested against a confined number of VMS systems listed in <<vms-table,Table {counter:table}>> below. Configuration instructions and usage examples of https://www.blickfeld.com/lidar-sensor-products/qbprotect/[QbProtect] with a particular VMS system can be accessed from the corresponding VMS column or the matching documentation subsection.

[NOTE]
====
QbProtect is not yet fully compliant with dedicated ONVIF https://www.onvif.org/profiles/[profiles].
====

[[vms-table]]
.Integration of QbProtect with VMS systems
[options="header",cols="2"]
|===
| Manufacturer | VMS

| https://senstar.com/products/video-management/senstar-symphony-common-operating-platform/[Senstar Corporation]
| xref:onvif/vms/senstar.adoc[Senstar Symphony]

| https://www.milestonesys.com/products/software/xprotect/[Milestone Systems]
| xref:onvif/vms/milestone.adoc[Milestone XProtect]

| https://www.geutebrueck.com/[Geutebrück GmbH]
| xref:onvif/vms/geutebrueck.adoc[G-Core]

| https://hxgnsecurity.com/products/hxgn-dc3/[Hexagon AB]
| xref:onvif/vms/hexagon.adoc[HxGN dC3]

| https://www.avigilon.com/vms/on-premise[Avigilon Corporation]
| xref:onvif/vms/avigilon.adoc[Avigilon Unity]

| https://www.keenfinity-group.com/xn/en/solutions/management-software/bvms/[Bosch GmbH]
| xref:onvif/vms/bosch.adoc[Bosch BVMS]
|===

