[#_blickfeld_base_AccessControl]
= Access Control

 
Access Control message which specifies the required access level and licenses for protocol entities. 
Protocol entities are usually gRPC services but can also be more fine grained on gRPC method 
and Protobuf field level.

.Available fields in blickfeld.base.AccessControl
|===
| Field | Type | Default | Unit

.2+| *level* | xref:blickfeld/base/options/access_control.adoc#_blickfeld_base_AccessControl_Level[Level] | - | - 
3+| Minimum access level required for entity

|===

[#_blickfeld_base_AccessControl_Level]
== Level

 
Available access levels 
 
The levels are ordered ascending, which means that each level also inherits the permissions 
of the levels above it.

.Available values for blickfeld.base.AccessControl.Level enum
[cols='25h,5,~']
|===
| Name | Value | Description

| LEVEL_UNSPECIFIED ^| 0 | Access level is not specified
| LEVEL_PUBLIC ^| 1 |  
Everyone can access 
 
The corresponding entities can be accessed by anyone who has access to the interface of the device. 
The access can not be disabled by the user.
| LEVEL_AUTHORIZED ^| 2 |  
Only authorized clients can access 
 
The corresponding entities can only be used by authorized clients. 
The access can be managed by clients with the ADMIN access level. 
If desired, the AUTHORIZED access level can be configured to act equally to the PUBLIC access level.
| LEVEL_ADMIN ^| 3 |  
Only administrative clients can access 
 
The corresponding entities are mainly used to configure the access tokens of the AUTHORIZED access level. 
It may also be used to manage configuration which might void the warranty or specification of the device.
| LEVEL_SUPPORT ^| 4 |  
Only clients of the Blickfeld support can access 
 
The corresponding entities can only be accessed by Blickfeld Support Tools & clients. 
The access tokens are bound to devices.
| LEVEL_PRODUCTION ^| 5 |  
Only clients in production can access 
 
The corresponding entities are used for end-of-line & re-work processes.
| LEVEL_DEVELOPER ^| 6 |  
Only Blickfeld developers can access
|===

