[#_blickfeld_base_ProtocolMaturity]
= Protocol Maturity

This message specifies the maturity of a protocol for customer- and production-facing APIs.

.Available fields in blickfeld.base.ProtocolMaturity
|===
| Field | Type | Default | Unit

.2+| *level* | xref:blickfeld/base/options/protocol_maturity.adoc#_blickfeld_base_ProtocolMaturity_Level[Level] | - | - 
3+| Simple level which describes maturity

|===

[#_blickfeld_base_ProtocolMaturity_Level]
== Level

This enumeration describes the maturity of a protocol. 
Please refer to the individual values. 
 
[IMPORTANT] 
APIs marked with the EXPERIMENTAL and DEPRECATED flags have to be handled with care. 
Please read through the definition. 
 
Please report if the protocol maturity of a service, method, and field does not fit 
e.g. if an EXPERIMENTAL field is required in an application and production use case.

.Available values for blickfeld.base.ProtocolMaturity.Level enum
[cols='25h,5,~']
|===
| Name | Value | Description

| LEVEL_UNSPECIFIED ^| 0 | Level is not set. 
Default level for services is EXPERIMENTAL. 
Default level for methods and fields is INHERITED.
| LEVEL_EXPERIMENTAL ^| 1 | APIs marked with this flag should be handled with care. 
They might not function as expected. 
Additionally it is not ensured that the APIs will ever be moved to the MAINTAINED level. 
They might be altered or removed in any upcoming release without further notice.
| LEVEL_MAINTAINED ^| 2 | APIs marked with this flag are actively maintained and released. 
They will not change their behavior without notices in the changelog. 
Breaking changes in a maintained APIs have to result in a major update of the module.
| LEVEL_DEPRECATED ^| 3 | APIs marked with this flag are no longer actively maintained. 
They will be removed in upcoming releases.
| LEVEL_INHERITED ^| 4 | The protocol maturity is inherited from the parent
|===

