= Scan Pattern

[#_blickfeld_system_config_ScanPattern]
== Scan Pattern

 
The scan pattern defines the movement of the mirrors. 
The key parameters of the pattern are the horizontal and vertical fields of view (FoV) as well as the number of scan lines per frame. 
The frame rate is defined by the total number of scan lines and the oscillation frequency of the mirrors which is fixed and 
device-specific. 


.Available fields in blickfeld.system.config.ScanPattern
|===
| Field | Type | Default | Unit

| *horizontal* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_Horizontal[Horizontal] | - | - 
| *vertical* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_Vertical[Vertical] | - | - 
| *pulse* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_Pulse[Pulse] | - | - 
.2+| *read_only* | bool| false | - 
3+| this is an read_only flag and it will be set if this is a default scan pattern, which can't be changed or deleted.

| *frame_rate* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_FrameRate[FrameRate] | - | - 
| *frame_mode* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_FrameMode[FrameMode] | FRAME_MODE_UP_DOWN | - 
|===

[#_blickfeld_system_config_ScanPattern_Horizontal]
=== Horizontal

 
This section defines the movement of the horizontal mirror. 
The mirror moves continuously with its own frequency. Each half-oscillation period of the mirror results in one scan line.

.Available fields in blickfeld.system.config.ScanPattern.Horizontal
|===
| Field | Type | Default | Unit

.2+| *field_of_view* | float| 1.57079637 | rad 
3+|  
Unit: [rad] 
– 
optical field of view of the horizontal mirror. 
Note: In v2.2* and below, this was defined as a mechanical FoV.

|===

[#_blickfeld_system_config_ScanPattern_Vertical]
=== Vertical

 
This section defines the movement of the vertical mirror within one frame. 
The mirror moves for from 0 degrees to the configured target FoV (up-ramping phase) and back to 0 degrees (down-ramping phase) with 
its eigenfrequency. The number of scanlines for each phase can be configured. Due to the dynamics of the mirror, a certain number of 
scan lines are required to reach the target FoV and then to reach 0 degrees again. Consequently, if the limit is reached, a lower 
number of scan lines requires a reduced FoV. Thus, a higher number of scan lines allows a larger vertical FoV. The vertical FoV is 
limited by the optical components. 
 
Note: Due to the time required for one scan line, the rounded even number of scan lines directly scales inverse proportionally with 
the frame rate.

.Available fields in blickfeld.system.config.ScanPattern.Vertical
|===
| Field | Type | Default | Unit

.2+| *field_of_view* | float| 0.87266463 | rad 
3+|  
Unit: [rad] 
– 
FoV in the center of the frame. 
Due to the eye shape of the scan pattern, the vertical FoV decreases the outer boundaries of the horizontal mirror.

.2+| *scanlines_up* | uint32| 40 | - 
3+|  
Configures the number of scan lines required for the up-ramping phase. 
During the up-ramping phase, the vertical mirror increases its amplitude from 0 degrees to the target FoV. Default: 200

.2+| *scanlines_down* | uint32| 40 | - 
3+|  
Configures the amount of scan lines required for the down-ramping phase. 
During the down-ramping phase, the vertical mirror decreases its amplitude from the target FoV to 0 degrees. Default: 30

.2+| *foveation* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_Vertical_Foveation[Foveation] | - | - 
3+| Optionally configures a foveated region.

|===

[#_blickfeld_system_config_ScanPattern_Vertical_Foveation]
==== Foveation

Configures a vertical field of view foveation. 
 
This enables the user to specify a region of interest with a different scanline density which is defined as the number of 
scanlines per degree of vertical field of view. For constant frame rate this allows increasing the resolution in the region of 
interest without having to reduce the vertical field of view.

.Available fields in blickfeld.system.config.ScanPattern.Vertical.Foveation
|===
| Field | Type | Default | Unit

.2+| *fraction* | float| 0.2 | - 
3+| The fraction of the field of view that the density factor is applies to. The allowed value range is [0.15, 0.85].

.2+| *density_factor* | float| 3 | - 
3+| The foveation density factor defines the ratio of scanline density and consequently point density inside the foveated region 
compared to outside of it.

.2+| *scanlines* | uint32| - | - 
3+| Read-only parameter showing the number of scanlines in the foveated region. If the frame mode is set to up-down or separate, 
this applies to both the up-ramping and down-ramping phase individually.

|===

[#_blickfeld_system_config_ScanPattern_Pulse]
=== Pulse

This section defines the pattern in which the laser pulses and captures sample points

.Available fields in blickfeld.system.config.ScanPattern.Pulse
|===
| Field | Type | Default | Unit

| *angle_spacing* | float| 0.0043633231 | rad 
.2+| *uniform* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern_Pulse_Uniform[Uniform] | - | - 
3+| Optional configure a uniform scan pattern

.2+| *disable_pre_pulse* | bool| false | - 
3+| Disable pre pulse 
 
Circumvents pulse aggregation issues e.g. when retro-reflectors appear in more than 70m and cause cross talk in the main pulse 
measurement. Note that this increases the minimum range.

|===

[#_blickfeld_system_config_ScanPattern_Pulse_Uniform]
==== Uniform

Configure the uniform scan pattern 
 
The classic scan pattern does not benefit uniformly from increasing the scanline count in a frame. The uniform scan pattern is an 
optimization that tries to provide an optimally homogeneous point cloud given the system's constraints. To configure the scan 
pattern, the vertical field of view, the target frame rate and the pulse mode are used.

.Available fields in blickfeld.system.config.ScanPattern.Pulse.Uniform
|===
| Field | Type | Default | Unit

.2+| *pulse_mode* | xref:blickfeld/eye_safety/data/pulse_mode.adoc[eye_safety.data.PulseMode] | PULSE_MODE_B | - 
3+| Pulse mode to use for the uniform scan pattern. This will overwrite the horizontal angle spacing.

|===

[#_blickfeld_system_config_ScanPattern_FrameRate]
=== Frame Rate

This section defines the frame rate of a scan pattern

.Available fields in blickfeld.system.config.ScanPattern.FrameRate
|===
| Field | Type | Default | Unit

.2+| *target* | double| - | Hz 
3+| Target frame rate used to synchronize the point clouds of multiple LiDAR devices in a sensor setup

.2+| *actual* | double| - | Hz 
3+| Read-only parameter for the actual frame rate the LiDAR is currently running at

.2+| *maximum* | double| - | Hz 
3+| IMPORTANT: This field is deprecated. It has been replaced by "actual" and will not be supported in future releases. 
 
Read-only parameter for maximum achievable frame rate of the scan pattern

|===

[#_blickfeld_system_config_ScanPattern_FrameMode]
=== Frame Mode

The frame mode specifies the point cloud frame's composition and can be used to fine tune the LiDAR to specific use cases.

.Available values for blickfeld.system.config.ScanPattern.FrameMode enum
[cols='25h,5,~']
|===
| Name | Value | Description

| FRAME_MODE_UNSPECIFIED ^| 0 | Unspecified frame mode
| FRAME_MODE_UP_DOWN ^| 1 | The laser will trigger both during up and downramping phase and a point cloud frame is the combination of the two. Points that 
are close in azimuth and elevation in both phases will be recorded up to two seconds apart, this mode is therefore recommended 
only for high frame rates or scenes without fast objects.
| FRAME_MODE_UP ^| 2 | The laser will only trigger during the upramping phase. Because no laser is fired during the downramping phase, this mode results 
in a more uniform motion deformation for fast objects.
| FRAME_MODE_SEPARATE ^| 3 | The laser will trigger both during up and downramping phase but separate point cloud frames will be emitted, which maximizes 
frame rate.
|===

[#_blickfeld_system_config_NamedScanPattern]
== Named Scan Pattern

Temporary container used for config storage 
TODO Remove when map type is supported.

.Available fields in blickfeld.system.config.NamedScanPattern
|===
| Field | Type | Default | Unit

| *name* | optional string| - | - 
| *scan_pattern* | xref:blickfeld/system/config/scan_pattern.adoc#_blickfeld_system_config_ScanPattern[ScanPattern] | - | - 
|===

