[#_blickfeld_system_config_TimeSynchronization]
= Time Synchronization

Conifguration for the system time synchronization 
 
The system time is used to fill timestamps in generated output data e.g. point cloud frames.

.Available fields in blickfeld.system.config.TimeSynchronization
|===
| Field | Type | Default | Unit

.2+| *ntp* | xref:blickfeld/system/config/time_synchronization.adoc#_blickfeld_system_config_TimeSynchronization_Ntp[Ntp] | - | - 
3+| Configuration for NTP time synchronization

.2+| *manual* | xref:blickfeld/system/config/time_synchronization.adoc#_blickfeld_system_config_TimeSynchronization_Manual[Manual] | - | - 
3+| Manual time configuration

.2+| *time_zone* | optional string| - | - 
3+| Configure time zone of device. 
 
Use ListTimeZones to retrieve the available time zones. 
 
Default: UTC

.2+| *serve_time* | bool| - | - 
3+| Serve the system time of this device to other devices in the network 
 
Starts a local, non-authoritative NTP server (stratum 10) which distributes the system time of this device. 
Access is restricted to the subnet of the device. 
It is intended for isolated networks without an NTP server and is managed automatically by the leader 
device of a swarm which uses manual time synchronization. 
 
[NOTE] 
The served time is only as accurate as the configured reference. 
The option has no effect when NTP time synchronization is used.

|===

[#_blickfeld_system_config_TimeSynchronization_Ntp]
== Ntp

Configuration message for NTP time synchronization

.Available fields in blickfeld.system.config.TimeSynchronization.Ntp
|===
| Field | Type | Default | Unit

.2+| *servers* | repeated string| - | - 
3+| List of NTP time servers which are to be used

|===

[#_blickfeld_system_config_TimeSynchronization_Manual]
== Manual

Manual time configuration 
 
[CAUTION] 
The device has no internal battery and no reference clock. 
Thus the timestamp has to be reconfigured after every power cycle and in regular intervals.

.Available fields in blickfeld.system.config.TimeSynchronization.Manual
|===
| Field | Type | Default | Unit

.2+| *timestamp* | uint64| - | ns 
3+| Unix reference timestamp 
 
[NOTE] 
The timestamp is ignored when unchanged. 
This prevents unintended time jumps when other configuration properties are modified.

|===

