name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    strategy:
      matrix:
        os: [windows-latest, windows-2025, windows-2022]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    - uses: lukka/get-cmake@latest
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'
    - name: compile
      run: | 
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -A x64 -DBUILD_SHARED_LIBS=OFF ..
        cmake --build . -j

  build-linux:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install debian dependencies
      run: sudo apt install -y libgrpc++-dev protobuf-compiler-grpc libprotobuf-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}

