# Tracking

xref:object_tracking/detection.adoc[Detected objects] from the previous step are tracked over time using various statistical properties. A motion model assuming constant velocity generates hypotheses about the xref:#_predict_tracks[expected future positions] based on the tracked object's speed and orientation.

## Parameters

The tracking algorithm is configurable via API. Documentation for the tracking configuration parameters and their default values is available in the xref:protocol:blickfeld/percept_pipeline/config/tracking.adoc[API definition].

## Algorithm

The goal of the tracking algorithm is to provide a consistent identification of objects in the scene over their whole lifecycle. The tracking algorithm works in four stages:

### Predict tracks

The expected position of all currently tracked objects is predicted. The prediction step uses the object's position, orientation and velocity to create a hypothesis about the next position of the track. The constant velocity motion model combined with the configured acceleration noise results in predictions which are scattered along the predicted object's path.

During the prediction step, the existence probability of each track is multiplied by the configured xref:#_parameters[survival probability]. This effectively reduces the confidence that the object is still present in the scene.

### Update tracks

This step receives the xref:object_tracking/detection.adoc[detected objects] and matches them to the predicted state of all currently tracked objects. When real measurements align well with the tracking parameters and the configured motion model, the state of the matching track is updated. The updated state will then contain the newly estimated velocity, the measured position, and a derived orientation based on the difference between the last positions.

Each track that could be updated with a new measurement has its existence probability increased.

### Create & delete tracks

Each detected object that could not be matched with an existing track is assigned a new track. To ensure consistent identification, the track receives a unique track-id. The new track's state is initialized using the detected object position and a default value for its existence probability.

Every track, which could not be matched with a detected object, gradually loses xref:#_predict_tracks[existence probability] after several tracking cycles. The track is deleted when the existence probability falls below the minimum existence probability threshold.

## Limitations

Difficult to parameterize:: Due to the wide range of configurable parameters, tuning the tracking module can be complex. Parameter values influence each other and may amplify unintended behavior.
+
[TIP]
====
The recommendation is to use the default values for all configuration parameters, as they should be sufficient to cover the majority of the target application scenarios. If these defaults still do not fully meet the requirements of your specific use case, please contact our support team for guidance on tailoring the configuration.
====
